Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

***
*******
***********
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 


*
**
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 


**
****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 


*
***
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
Traceback (most recent call last):
  File "C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py", line 2, in <module>
    print((4-i)*''+1(2*i-1)*'*')
TypeError: 'int' object is not callable
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
Traceback (most recent call last):
  File "C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py", line 2, in <module>
    print((4-i)*''(2*i-1)*'*')
TypeError: 'str' object is not callable
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern2.py 
******
 *****
  ****
   ***
    **
     *
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern2.py 
******
 *****
  ****
   ***
    **
     *
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 


*
**
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
*
***
*****
*******
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
Traceback (most recent call last):
  File "C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py", line 1, in <module>
    for i in range(0,4,0):
ValueError: range() arg 3 must not be zero
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 

*
***
*****
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
Traceback (most recent call last):
  File "C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py", line 2, in <module>
    print(((4-i)+1)*' '(2*i-1)*'*')
TypeError: 'str' object is not callable
>>> 
 RESTART: C:\Users\SHIV\AppData\Local\Programs\Python\Python37-32\pattern.py 
     
    *
   ***
  *****
 *******
>>> 
